/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BalanceRouteImport } from './routes/balance'
import { Route as PopolnenieRouteImport } from './routes/popolnenie'
import { Route as ApiPublicKaspi_payRouteImport } from './routes/api/public/kaspi_pay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BalanceRoute = BalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const PopolnenieRoute = PopolnenieRouteImport.update({
  id: '/popolnenie',
  path: '/popolnenie',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKaspi_payRoute = ApiPublicKaspi_payRouteImport.update({
  id: '/api/public/kaspi_pay',
  path: '/api/public/kaspi_pay',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/balance': typeof BalanceRoute
  '/popolnenie': typeof PopolnenieRoute
  '/api/public/kaspi_pay': typeof ApiPublicKaspi_payRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/balance': typeof BalanceRoute
  '/popolnenie': typeof PopolnenieRoute
  '/api/public/kaspi_pay': typeof ApiPublicKaspi_payRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/balance': typeof BalanceRoute
  '/popolnenie': typeof PopolnenieRoute
  '/api/public/kaspi_pay': typeof ApiPublicKaspi_payRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/admin' | '/balance' | '/popolnenie' | '/api/public/kaspi_pay'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/balance' | '/popolnenie' | '/api/public/kaspi_pay'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/balance'
    | '/popolnenie'
    | '/api/public/kaspi_pay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BalanceRoute: typeof BalanceRoute
  PopolnenieRoute: typeof PopolnenieRoute
  ApiPublicKaspi_payRoute: typeof ApiPublicKaspi_payRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balance': {
      id: '/balance'
      path: '/balance'
      fullPath: '/balance'
      preLoaderRoute: typeof BalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/popolnenie': {
      id: '/popolnenie'
      path: '/popolnenie'
      fullPath: '/popolnenie'
      preLoaderRoute: typeof PopolnenieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kaspi_pay': {
      id: '/api/public/kaspi_pay'
      path: '/api/public/kaspi_pay'
      fullPath: '/api/public/kaspi_pay'
      preLoaderRoute: typeof ApiPublicKaspi_payRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BalanceRoute: BalanceRoute,
  PopolnenieRoute: PopolnenieRoute,
  ApiPublicKaspi_payRoute: ApiPublicKaspi_payRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
